name: Log Commit Messages

on:
  pull_request:
    types:
      - opened

jobs:
  log_commit_messages:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Log Commit Messages
        run: |
          echo "# Changelog" > CHANGELOG.md
          git log --pretty=format:"- %s (%an)" >> CHANGELOG.md

      - name: Commit and Push Changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update CHANGELOG.md
          commit_options: '--no-verify'
          branch: ${{ github.ref }}
